#!/usr/bin/env python
# -*- coding: UTF8 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Mon Feb 17 18:30:03 2014
#
from wxui import *
import wx
import gettext


# end of class MainFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.App(False)
    frame_1 = MainFrame(None)
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()